@startuml flowchart-diagram
	|source| Источник
	|ptk| ПТК
	|buffer| Буфер
	|worker| Диспетчер

	|source|
	split
		-[hidden]->
		start
		:Отправить заявку в систему]

		|ptk|
		:Определение приоритета заявки;
		:Отправить заявку в буфер]

		|buffer|
		if (Есть место в буфере?) then (да)
			#PaleGreen :Поставить заявку в очередь]
			detach
		else (нет)
			:Поиск заявки с наименьшим\nприоритетом;
			if (Приоритет входящей заявки выше?) then (да)
				:Отклонить найденную заявку]
				#PaleGreen :Поставить заявку в очередь]
				detach
			else (нет)
				:Отклонить заявку]
				stop
			endif
		endif
	split again
		|ptk|
		-[hidden]->
		:Изменение состояния заявки;
		:Сообщить об изменении статуса источнику]
		stop
	split again
		|worker|
		-[hidden]->
		start
		:Запросить пакет заявок в буфере]
		|buffer|
		:Поиск приоритетного пакета;
		if (Пакет найден?) then (да)
			:Передать пакет диспетчеру]
		else (нет)
			stop
		endif
		|worker|
		while (Заявка выполнена?) is (нет)
			:Обработка заявки]
		endwhile (да)
		:Записать результат выполнения]
		:Закрыть заявку]
		stop
	
	end split
@enduml